server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:127.0.0.1:3306/e3mall-32
    username: root
    password: aa
  application:
    name: upload_service
  servlet:
    multipart:
      max_file_size: 5MB
fdfs:
  so-timeout: 3000
  connect-timeout: 1000
  thumb-image:
    width: 60
    height: 60
  tracker-list:
    - 192.168.0.108:22122